import { useCallback, useMemo } from "react";

import { ensureUniqueAutoGeneratedUuids } from "@mooreseditor/plugin-sdk";
import { useCopyPaste } from "@mooreseditor/plugin-sdk";

import type {
  Schema,
  ObjectSchema,
  ValueSchema,
} from "@mooreseditor/plugin-sdk";

interface UseClipboardAppendOptions {
  schemaItems?: Schema | ValueSchema;
  arrayData: any[];
  onDataChange?: (value: any[]) => void;
}

export function useClipboardAppend({
  schemaItems,
  arrayData,
  onDataChange,
}: UseClipboardAppendOptions) {
  const objectItemSchema = useMemo(() => {
    if (!schemaItems || !("type" in schemaItems)) {
      return undefined;
    }

    return schemaItems.type === "object"
      ? (schemaItems as ObjectSchema)
      : undefined;
  }, [schemaItems]);

  const handleAppendFromClipboard = useCallback(
    (newValue: any) => {
      if (!onDataChange) {
        return;
      }

      let processedValue = newValue;
      let regeneratedCount = 0;

      if (schemaItems && "type" in schemaItems) {
        const { value: uniqueValue, regeneratedPaths } =
          ensureUniqueAutoGeneratedUuids(newValue, schemaItems, arrayData);
        processedValue = uniqueValue;
        regeneratedCount = regeneratedPaths.length;
      }

      const newArray = [...arrayData];
      newArray.push(processedValue);
      onDataChange(newArray);

      if (regeneratedCount > 0) {
        return {
          successMessage: `値を貼り付けました（${regeneratedCount}件のguidを再生成しました）`,
        };
      }
    },
    [arrayData, onDataChange, schemaItems],
  );

  const { handlePaste: handlePasteNewItem } = useCopyPaste(
    null,
    handleAppendFromClipboard,
    (objectItemSchema ?? { type: "object" }) as Schema,
  );

  return { objectItemSchema, handlePasteNewItem };
}
