import { validate as validateUuid } from "uuid";
import { describe, expect, it } from "vitest";

import { createInitialValue } from "../../createInitialValue";
import { DataInitializer } from "../dataInitializer";

import type { ObjectSchema } from "../../../schema";

describe("DataInitializer", () => {
  describe("AutoIncrement", () => {
    it("should handle autoIncrement for integer fields", () => {
      const schema: ObjectSchema = {
        type: "object",
        properties: [
          {
            key: "id",
            type: "integer",
            optional: false,
            autoIncrement: { direction: "asc", startWith: 1, step: 1 },
          },
          { key: "name", type: "string", optional: false },
        ],
      };

      const existingData = [
        { id: 1, name: "Item 1" },
        { id: 2, name: "Item 2" },
      ];

      const initializer = new DataInitializer(existingData);
      const result = initializer.createRequiredValue(schema);

      expect(result).toEqual({
        id: 3,
        name: "",
      });
    });
  });

  describe("Circular references", () => {
    it("should handle circular references gracefully", () => {
      const schema: ObjectSchema = {
        type: "object",
        ref: "node",
        properties: [
          { key: "name", type: "string", optional: false },
          {
            key: "children",
            type: "array",
            items: {
              type: "object",
              ref: "node", // 循環参照
              properties: [],
            },
          },
        ],
      };

      const initializer = new DataInitializer();
      const result = initializer.createRequiredValue(schema);

      expect(result).toEqual({
        name: "",
        children: [],
      });
    });
  });

  describe("Runtime schema boundaries", () => {
    it.each([
      { type: "object", properties: {} },
      { type: "object", properties: [null] },
      { type: "array" },
      { type: "enum", options: null },
    ])("returns null for a malformed known schema: %j", (schema) => {
      const initializer = new DataInitializer();

      expect(() =>
        initializer.createRequiredValue(schema as never),
      ).not.toThrow();
      expect(initializer.createRequiredValue(schema as never)).toBeNull();
      expect(() =>
        createInitialValue(schema as never, [], false),
      ).not.toThrow();
      expect(createInitialValue(schema as never, [], false)).toBeNull();
    });

    it("keeps the full-initialization primitive defaults observable", () => {
      expect(createInitialValue({ type: "string" }, [], false)).toBe("");
      expect(
        createInitialValue(
          { type: "number", default: 2.5 },
          [],
          false,
        ),
      ).toBe(2.5);

      const uuid = createInitialValue(
        { type: "uuid", autoGenerated: true },
        [],
        false,
      );
      expect(uuid).toEqual(expect.any(String));
      expect(validateUuid(uuid)).toBe(true);
    });
  });
});
