import type { AutoIncrementOptions } from "../../utils/autoIncrement";

export type RefString = string;

export interface StyleOptions {
  multiline?: boolean;
  // Additional style options can be added here in the future
}

export interface ObjectSchema {
  type: "object";
  openedByDefault?: boolean;
  properties?: Array<ObjectPropertySchema>;
  ref?: string;
  optional?: boolean;
}

export type ObjectPropertySchema = Schema & {
  key: string;
};

export interface ArraySchema {
  type: "array";
  items: ValueSchema;
  minLength?: number;
  maxLength?: number;
  openedByDefault?: boolean;
  default?: any[];
}

export interface StringSchema {
  type: "string";
  optional?: boolean;
  default?: string;
  style?: StyleOptions;
  foreignKey?: ForeignKeyConfig;
}

export interface EnumSchema {
  type: "enum";
  optional?: boolean;
  options: Array<string>;
  default?: this["options"][number];
}

export interface ForeignKeyConfig {
  schemaId: string;
  foreignKeyIdPath: string;
  displayElementPath: string;
  hierarchyDisplayPaths?: string[]; // Optional: parent paths to collect for hierarchical display (e.g., "/data/[*]/categoryName")
}

export interface UuidSchema {
  type: "uuid";
  optional?: boolean;
  autoGenerated?: boolean;
  foreignKey?: ForeignKeyConfig;
}

// foreignKey を付与できる schema type 一覧。
// 新しく対応 type を増やすときは、ここに追記したうえで該当 *Schema interface に
// `foreignKey?: ForeignKeyConfig` を生やす。これで dispatch 側の判定が自動追従する。
export const FOREIGN_KEY_SUPPORTED_TYPES = ["uuid", "string"] as const;
export type ForeignKeySupportedType =
  (typeof FOREIGN_KEY_SUPPORTED_TYPES)[number];

export function supportsForeignKey(
  type: string | undefined,
): type is ForeignKeySupportedType {
  return (FOREIGN_KEY_SUPPORTED_TYPES as readonly string[]).includes(
    type ?? "",
  );
}

export interface IntegerSchema {
  type: "integer";
  optional?: boolean;
  default?: number;
  min?: number;
  max?: number;
  autoIncrement?: AutoIncrementOptions;
}

export interface NumberSchema {
  type: "number";
  optional?: boolean;
  default?: number;
  min?: number;
  max?: number;
  autoIncrement?: AutoIncrementOptions;
}

export interface Vector2 {
  type: "vector2";
  optional?: boolean;
  default?: [number, number];
}

export interface Vector3 {
  type: "vector3";
  optional?: boolean;
  default?: [number, number, number];
}

export interface Vector4 {
  type: "vector4";
  optional?: boolean;
  default?: [number, number, number, number];
}

export interface Vector2Int {
  type: "vector2Int";
  optional?: boolean;
  default?: [number, number];
}

export interface Vector3Int {
  type: "vector3Int";
  optional?: boolean;
  default?: [number, number, number];
}

export interface Vector4Int {
  type: "vector4Int";
  optional?: boolean;
  default?: [number, number, number, number];
}

export interface BooleanSchema {
  type: "boolean";
  optional?: boolean;
  default?: boolean;
}

export interface SwitchSchema {
  switch: string;
  cases: Array<
    {
      when: string | number | boolean;
    } & ValueSchema
  >;
  optional?: boolean;
}

export type PrimitiveSchema =
  | StringSchema
  | EnumSchema
  | UuidSchema
  | IntegerSchema
  | NumberSchema
  | BooleanSchema
  | Vector2
  | Vector3
  | Vector4
  | Vector2Int
  | Vector3Int
  | Vector4Int;

export type StructedSchema = ObjectSchema | ArraySchema;

export type ValueSchema = StructedSchema | PrimitiveSchema;

export type Schema = ValueSchema | SwitchSchema;

export type SchemaContainer = ArraySchema & {
  id: string;
  sortOrder?: number;
};
