import {
  afterEach,
  beforeEach,
  describe,
  expect,
  it,
  vi,
} from "vitest";

import { ensureUniqueAutoGeneratedUuids } from "./ensureUniqueAutoGeneratedUuids";
import * as generateUuidModule from "./generateUuid";

import type { ObjectSchema } from "../libs/schema/types";

const toDeterministicUuid = (
  value: number,
): `${string}-${string}-${string}-${string}-${string}` => {
  const suffix = value.toString().padStart(12, "0");
  return `00000000-0000-0000-0000-${suffix}`;
};

describe("ensureUniqueAutoGeneratedUuids", () => {
  beforeEach(() => {
    let counter = 0;
    vi.spyOn(generateUuidModule, "generateUuid").mockImplementation(() => {
      counter += 1;
      return toDeterministicUuid(counter);
    });
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it("regenerates duplicated guid at top level", () => {
    const schema: ObjectSchema = {
      type: "object",
      properties: [
        { key: "guid", type: "uuid", autoGenerated: true },
        { key: "label", type: "string" },
      ],
    };

    const existing = [
      { guid: "guid-1", label: "foo" },
      { guid: "guid-2", label: "bar" },
    ];

    const input = { guid: "guid-1", label: "baz" };
    const result = ensureUniqueAutoGeneratedUuids(input, schema, existing);

    expect(result.value.guid).toBe("00000000-0000-0000-0000-000000000001");
    expect(result.value.label).toBe("baz");
    expect(result.regeneratedPaths).toEqual(["guid"]);
  });

  it("keeps unique guid untouched", () => {
    const schema: ObjectSchema = {
      type: "object",
      properties: [
        { key: "guid", type: "uuid", autoGenerated: true },
        { key: "label", type: "string" },
      ],
    };

    const existing = [{ guid: "guid-1", label: "foo" }];
    const input = { guid: "guid-2", label: "bar" };

    const result = ensureUniqueAutoGeneratedUuids(input, schema, existing);

    expect(result.value.guid).toBe("guid-2");
    expect(result.regeneratedPaths).toEqual([]);
  });

  it("regenerates nested duplicated guid within array items", () => {
    const childSchema: ObjectSchema = {
      type: "object",
      properties: [
        { key: "id", type: "uuid", autoGenerated: true },
        { key: "name", type: "string" },
      ],
    };
    const schema: ObjectSchema = {
      type: "object",
      properties: [
        { key: "guid", type: "uuid", autoGenerated: true },
        { key: "children", type: "array", items: childSchema },
      ],
    };

    const existing = [
      {
        guid: "guid-1",
        children: [
          { id: "child-1", name: "apple" },
          { id: "child-2", name: "banana" },
        ],
      },
    ];

    const input = {
      guid: "guid-3",
      children: [
        { id: "child-1", name: "cherry" },
        { id: "child-1", name: "durian" },
      ],
    };

    const result = ensureUniqueAutoGeneratedUuids(input, schema, existing);

    const regeneratedChildIds = result.value.children.map(
      (child: any) => child.id,
    );
    expect(new Set(regeneratedChildIds).size).toBe(
      result.value.children.length,
    );
    expect(result.regeneratedPaths).toEqual([
      "children.[*].id",
      "children.[*].id",
    ]);
  });
});
