import { generateUuid } from "./generateUuid";

import type {
  ArraySchema,
  ObjectSchema,
  Schema,
  ValueSchema,
} from "../libs/schema/types";

interface UniqueUuidResult {
  value: any;
  regeneratedPaths: string[];
}

type GuidPathKey = string;

/**
 * Ensure pasted value does not duplicate autoGenerated uuid fields within the target array.
 * The implementation is schema-driven and works with arbitrarily nested arrays/objects.
 */
export function ensureUniqueAutoGeneratedUuids(
  value: any,
  schema: Schema | ValueSchema | undefined,
  existingItems: any[],
): UniqueUuidResult {
  const clonedValue = structuredClone(value);

  if (!schema || !("type" in schema)) {
    return { value: clonedValue, regeneratedPaths: [] };
  }

  const existingGuidMap = new Map<GuidPathKey, Set<string>>();
  existingItems.forEach((item) => {
    collectGuidValues(item, schema, [], existingGuidMap);
  });

  const regeneratedPaths: string[] = [];
  const processedValue = processValue(
    clonedValue,
    schema,
    [],
    existingGuidMap,
    regeneratedPaths,
  );

  return { value: processedValue, regeneratedPaths };
}

function collectGuidValues(
  data: any,
  schema: Schema | ValueSchema,
  path: string[],
  guidMap: Map<GuidPathKey, Set<string>>,
) {
  if (!schema || !("type" in schema)) {
    return;
  }

  switch (schema.type) {
    case "uuid":
      if (schema.autoGenerated && typeof data === "string") {
        const key = pathToKey(path);
        getOrCreateGuidSet(guidMap, key).add(data);
      }
      break;
    case "object":
      if (!data || typeof data !== "object" || Array.isArray(data)) {
        return;
      }
      (schema as ObjectSchema).properties?.forEach((property) => {
        const { key, ...childSchema } = property;
        collectGuidValues(
          data[key],
          childSchema as Schema,
          [...path, key],
          guidMap,
        );
      });
      break;
    case "array": {
      if (!Array.isArray(data)) {
        return;
      }
      const arraySchema = schema as ArraySchema;
      data.forEach((item) => {
        collectGuidValues(item, arraySchema.items, [...path, "*"], guidMap);
      });
      break;
    }
    default:
      break;
  }
}

function processValue(
  data: any,
  schema: Schema | ValueSchema,
  path: string[],
  guidMap: Map<GuidPathKey, Set<string>>,
  regeneratedPaths: string[],
): any {
  if (!schema || !("type" in schema)) {
    return data;
  }

  switch (schema.type) {
    case "uuid":
      if (!schema.autoGenerated || typeof data !== "string") {
        return data;
      }
      return ensureUniqueGuidValue(data, path, guidMap, regeneratedPaths);
    case "object":
      if (!data || typeof data !== "object" || Array.isArray(data)) {
        return data;
      }
      return processObjectValue(
        data,
        schema as ObjectSchema,
        path,
        guidMap,
        regeneratedPaths,
      );
    case "array":
      if (!Array.isArray(data)) {
        return data;
      }
      return processArrayValue(
        data,
        schema as ArraySchema,
        path,
        guidMap,
        regeneratedPaths,
      );
    default:
      return data;
  }
}

function processObjectValue(
  data: Record<string, any>,
  schema: ObjectSchema,
  path: string[],
  guidMap: Map<GuidPathKey, Set<string>>,
  regeneratedPaths: string[],
) {
  const result: Record<string, any> = { ...data };
  schema.properties?.forEach((property) => {
    const { key, ...childSchema } = property;
    if (!(key in result)) {
      return;
    }
    result[key] = processValue(
      result[key],
      childSchema as Schema,
      [...path, key],
      guidMap,
      regeneratedPaths,
    );
  });
  return result;
}

function processArrayValue(
  data: any[],
  schema: ArraySchema,
  path: string[],
  guidMap: Map<GuidPathKey, Set<string>>,
  regeneratedPaths: string[],
) {
  return data.map((item) =>
    processValue(
      item,
      schema.items,
      [...path, "*"],
      guidMap,
      regeneratedPaths,
    ),
  );
}

function ensureUniqueGuidValue(
  value: string,
  path: string[],
  guidMap: Map<GuidPathKey, Set<string>>,
  regeneratedPaths: string[],
) {
  const key = pathToKey(path);
  const guidSet = getOrCreateGuidSet(guidMap, key);

  if (!guidSet.has(value)) {
    guidSet.add(value);
    return value;
  }

  let newValue = value;
  do {
    newValue = generateUuid();
  } while (guidSet.has(newValue));

  guidSet.add(newValue);
  regeneratedPaths.push(pathToDisplay(path));
  return newValue;
}

function getOrCreateGuidSet(
  guidMap: Map<GuidPathKey, Set<string>>,
  key: GuidPathKey,
) {
  let set = guidMap.get(key);
  if (!set) {
    set = new Set<string>();
    guidMap.set(key, set);
  }
  return set;
}

function pathToKey(path: string[]) {
  return path.join(".");
}

function pathToDisplay(path: string[]) {
  if (path.length === 0) {
    return "(root)";
  }
  return path
    .map((segment) => (segment === "*" ? "[*]" : segment))
    .join(".");
}
