import { validate as validateUuid } from "uuid";
import { describe, expect, it } from "vitest";

import { createPrimitiveDefaultValue } from "./primitiveDefaultValue";

import type { PrimitiveSchema } from "../schema";

describe("createPrimitiveDefaultValue", () => {
  it.each([
    { type: "futureKind" },
    { type: null },
  ])("returns null for an unsupported runtime discriminator: $type", (schema) => {
    expect(
      createPrimitiveDefaultValue(schema as unknown as PrimitiveSchema),
    ).toBeNull();
  });

  it.each<[PrimitiveSchema, unknown]>([
    [{ type: "string" }, ""],
    [{ type: "enum", options: ["first", "second"] }, ""],
    [{ type: "uuid" }, ""],
    [{ type: "integer" }, 0],
    [{ type: "number" }, 0],
    [{ type: "boolean" }, false],
    [{ type: "vector2" }, [0, 0]],
    [{ type: "vector3" }, [0, 0, 0]],
    [{ type: "vector4" }, [0, 0, 0, 0]],
    [{ type: "vector2Int" }, [0, 0]],
    [{ type: "vector3Int" }, [0, 0, 0]],
    [{ type: "vector4Int" }, [0, 0, 0, 0]],
  ])("creates the fallback for $type", (schema, expected) => {
    expect(createPrimitiveDefaultValue(schema)).toEqual(expected);
  });

  it.each<[PrimitiveSchema, unknown]>([
    [{ type: "string", default: "custom" }, "custom"],
    [
      { type: "enum", options: ["first", "second"], default: "second" },
      "second",
    ],
    [{ type: "integer", default: 42 }, 42],
    [{ type: "number", default: 3.5 }, 3.5],
    [{ type: "boolean", default: true }, true],
    [{ type: "vector2", default: [1, 2] }, [1, 2]],
    [{ type: "vector3", default: [1, 2, 3] }, [1, 2, 3]],
    [{ type: "vector4", default: [1, 2, 3, 4] }, [1, 2, 3, 4]],
    [{ type: "vector2Int", default: [5, 6] }, [5, 6]],
    [{ type: "vector3Int", default: [5, 6, 7] }, [5, 6, 7]],
    [{ type: "vector4Int", default: [5, 6, 7, 8] }, [5, 6, 7, 8]],
  ])("uses the explicit default for $type", (schema, expected) => {
    expect(createPrimitiveDefaultValue(schema)).toEqual(expected);
  });

  it("auto-generates a valid, unique UUID when requested", () => {
    const first = createPrimitiveDefaultValue({
      type: "uuid",
      autoGenerated: true,
    });
    const second = createPrimitiveDefaultValue({
      type: "uuid",
      autoGenerated: true,
    });

    expect(first).toEqual(expect.any(String));
    expect(validateUuid(first as string)).toBe(true);
    expect(second).not.toBe(first);
  });
});
