import { isPrimitiveSchemaType } from "../schema";

import { generateUuid } from "./generateUuid";

import type { PrimitiveSchema } from "../schema";

type PrimitiveDefaultValueHandlers = {
  [Type in PrimitiveSchema["type"]]: (
    schema: Extract<PrimitiveSchema, { type: Type }>,
  ) => unknown;
};

const primitiveDefaultValueHandlers = {
  string: (schema) => schema.default ?? "",
  enum: (schema) => schema.default ?? "",
  uuid: (schema) => (schema.autoGenerated ? generateUuid() : ""),
  // autoIncrement is applied by the enclosing object initializer.
  integer: (schema) => schema.default ?? 0,
  number: (schema) => schema.default ?? 0,
  boolean: (schema) => schema.default ?? false,
  vector2: (schema) => schema.default ?? [0, 0],
  vector3: (schema) => schema.default ?? [0, 0, 0],
  vector4: (schema) => schema.default ?? [0, 0, 0, 0],
  vector2Int: (schema) => schema.default ?? [0, 0],
  vector3Int: (schema) => schema.default ?? [0, 0, 0],
  vector4Int: (schema) => schema.default ?? [0, 0, 0, 0],
} satisfies PrimitiveDefaultValueHandlers;

export function createPrimitiveDefaultValue(schema: PrimitiveSchema): unknown {
  if (!isPrimitiveSchemaType(schema.type)) {
    return null;
  }

  // The discriminant selects the handler for this exact schema variant. TypeScript
  // cannot preserve that key/argument correlation through an indexed union call.
  return primitiveDefaultValueHandlers[schema.type](schema as never);
}
