import { act, renderHook } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";

import { useEdgeTypeDialogState } from "./useEdgeTypeDialogState";

import type { SchemaMeta } from "../../../utils/schemaMeta";
import type { Column } from "@mooreseditor/plugin-sdk";

function createCraftRecipeMeta(): SchemaMeta {
  return {
    schemaId: "craftRecipes",
    guidField: "craftRecipeGuid",
    nameField: "craftRecipeName",
    dataArrayPath: "data",
    elementSchema: {
      type: "object",
      properties: [
        { key: "craftRecipeGuid", type: "uuid", autoGenerated: true },
        { key: "craftRecipeName", type: "string", default: "Recipe" },
      ],
    },
  };
}

describe("useEdgeTypeDialogState", () => {
  it("removes a newly created draft recipe when the dialog is cancelled", () => {
    let columns: Column[] = [{ title: "craftRecipes", data: { data: [] } }];
    const setJsonData = vi.fn((updater) => {
      columns = typeof updater === "function" ? updater(columns) : updater;
    });

    const { result } = renderHook(() =>
      useEdgeTypeDialogState({
        opened: true,
        onConfirm: vi.fn(),
        onCancel: vi.fn(),
        jsonData: columns,
        setJsonData,
        schemaMetas: new Map([["craftRecipes", createCraftRecipeMeta()]]),
        sourceNode: {
          id: "source",
          type: "item",
          data: { masterGuid: "item-a" },
        } as any,
        targetNode: {
          id: "target",
          type: "item",
          data: { masterGuid: "item-b" },
        } as any,
        onMarkDirty: vi.fn(),
      }),
    );

    act(() => {
      result.current.handleCreateRecipe("craftRecipe");
    });
    expect(columns[0].data.data).toHaveLength(1);

    act(() => {
      result.current.handleCancel();
    });

    expect(columns[0].data.data).toHaveLength(0);
  });
});
