/**
 * @deprecated Tests moved to domain/nodeGraph/__tests__/masterRecordCreation.test.ts
 * This file is kept for backwards compatibility but re-tests through the re-export shim.
 */
import { describe, expect, it } from "vitest";

import {
  canCreateMasterRecordForNode,
  createMasterRecordForNode,
} from "./masterRecordCreation";

import type { SchemaMeta } from "./schemaMeta";
import type { Column } from "../../hooks/useJson";
import type { ObjectSchema } from "../../libs/schema/types";

const UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

const itemElementSchema: ObjectSchema = {
  type: "object",
  properties: [
    { key: "guid", type: "uuid", autoGenerated: true },
    { key: "name", type: "string" },
  ],
};

function buildSchemaMetaMap(): Map<string, SchemaMeta> {
  return new Map<string, SchemaMeta>([
    [
      "items",
      {
        schemaId: "items",
        guidField: "guid",
        nameField: "name",
        dataArrayPath: "data",
        elementSchema: itemElementSchema,
      },
    ],
  ]);
}

describe("masterRecordCreation (via re-export)", () => {
  it("creates a new record", () => {
    const schemaMetas = buildSchemaMetaMap();
    const columns: Column[] = [{ title: "items", data: { data: [] } }];

    const result = createMasterRecordForNode("item", columns, schemaMetas);

    expect(result).not.toBeNull();
    expect(result?.masterGuid).toMatch(UUID_RE);
    expect(result?.displayName).toBe("New Item");
  });

  it("returns null when column missing", () => {
    const schemaMetas = buildSchemaMetaMap();
    expect(canCreateMasterRecordForNode("item", [], schemaMetas)).toBe(false);
  });
});
