// @mooreseditor/plugin-sdk 公開エントリ。
// 各 Task で schema / components / hooks / utils / contract を順次 re-export していく。
export type { HostAPI, PluginView, PluginManifest } from "./contract/types";
export * from "./schema";
export * from "./utils/autoIncrement";
export * from "./utils/generateUuid";
export * from "./utils/ensureUniqueAutoGeneratedUuids";
export * from "./utils/switchFieldProcessor";
export * from "./utils/vectorConverter";
export * from "./utils/pathResolver";
export * from "./utils/foreignKeyResolver";
export * from "./utils/deepMerge";
export * from "./utils/dataInitializer";
export * from "./utils/createInitialValue";
export * from "./utils/schemaToZod";
export * from "./types/json";
