import { describe, expect, it } from "vitest";

import {
  canCreateMasterRecordForNode,
  createMasterRecordForNode,
} from "../masterRecordCreation";

import type { SchemaMeta } from "../schemaMeta";
import type { Column, JsonObject } from "../../data/types";
import type { ObjectSchema } from "../../schema/types";

const UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

const itemElementSchema: ObjectSchema = {
  type: "object",
  properties: [
    { key: "guid", type: "uuid", autoGenerated: true },
    { key: "name", type: "string" },
  ],
};

function buildSchemaMetaMap(): Map<string, SchemaMeta> {
  return new Map<string, SchemaMeta>([
    [
      "items",
      {
        schemaId: "items",
        guidField: "guid",
        nameField: "name",
        dataArrayPath: "data",
        elementSchema: itemElementSchema,
      },
    ],
    [
      "research",
      {
        schemaId: "research",
        guidField: "guid",
        nameField: "name",
        dataArrayPath: "data",
        elementSchema: itemElementSchema,
      },
    ],
  ]);
}

describe("masterRecordCreation", () => {
  it("creates a new item record and returns node metadata", () => {
    const schemaMetas = buildSchemaMetaMap();
    const columns: Column[] = [
      {
        title: "items",
        data: {
          data: [],
        },
      },
    ];

    const result = createMasterRecordForNode("item", columns, schemaMetas);

    expect(result).not.toBeNull();
    expect(result?.masterGuid).toMatch(UUID_RE);
    expect(result?.displayName).toBe("New Item");

    const updatedData = result?.updatedColumns[0].data as JsonObject;
    const records = updatedData.data as unknown[];
    expect(records).toHaveLength(1);
    const record = records[0] as Record<string, unknown>;
    expect(record.guid).toMatch(UUID_RE);
    expect(record.name).toBe("New Item");
  });

  it("generates unique default names for research records", () => {
    const schemaMetas = buildSchemaMetaMap();
    const columns: Column[] = [
      {
        title: "research",
        data: {
          data: [
            { guid: "r-1", name: "New Research" },
            { guid: "r-2", name: "New Research 2" },
          ],
        },
      },
    ];

    const result = createMasterRecordForNode("research", columns, schemaMetas);

    expect(result).not.toBeNull();
    expect(result?.displayName).toBe("New Research 3");

    const updatedData = result?.updatedColumns[0].data as JsonObject;
    const records = updatedData.data as unknown[];
    expect(records).toHaveLength(3);
    const newRecord = records[2] as Record<string, unknown>;
    expect(newRecord.guid).toMatch(UUID_RE);
    expect(newRecord.name).toBe("New Research 3");
  });

  it("returns null when the target column does not exist", () => {
    const schemaMetas = buildSchemaMetaMap();
    const columns: Column[] = [];

    const result = createMasterRecordForNode("item", columns, schemaMetas);

    expect(result).toBeNull();
    expect(canCreateMasterRecordForNode("item", columns, schemaMetas)).toBe(
      false,
    );
  });
});
