import { describe, expect, it } from "vitest";

import {
  canCreateMasterRecordForNode,
  createMasterRecordForNode,
} from "./masterRecordCreation";

import type { SchemaMeta } from "./schemaMeta";
import type { Column } from "@mooreseditor/plugin-sdk";

const questMeta: SchemaMeta = {
  schemaId: "quests",
  guidField: "questGuid",
  nameField: "questName",
  dataArrayPath: "data",
  elementSchema: {
    type: "object",
    properties: [
      { key: "questGuid", type: "uuid", autoGenerated: true },
      { key: "questName", type: "string", default: "New Quest" },
    ],
  },
};

describe("masterRecordCreation dynamic schema ids", () => {
  it("creates records for arbitrary node types resolved from SchemaMeta", () => {
    const columns: Column[] = [{ title: "quests", data: { data: [] } }];
    const metas = new Map([["quests", questMeta]]);

    expect(canCreateMasterRecordForNode("quest" as any, columns, metas)).toBe(
      true,
    );

    const result = createMasterRecordForNode("quest" as any, columns, metas);

    expect(result?.updatedColumns[0].data.data).toHaveLength(1);
    expect(result?.displayName).toBe("New Quest");
  });
});
