import { describe, expect, it } from "vitest";

import {
  canCreateMasterRecordForNode,
  createMasterRecordForNode,
} from "./masterRecordCreation";

import type { SchemaMeta } from "./schemaMeta";
import type { Column, ObjectSchema } from "@moorestech/mooreseditor-plugin-sdk";

const itemElementSchema: ObjectSchema = {
  type: "object",
  properties: [
    { key: "guid", type: "uuid", autoGenerated: true },
    { key: "name", type: "string" },
  ],
};

function buildSchemaMetaMap(): Map<string, SchemaMeta> {
  return new Map<string, SchemaMeta>([
    [
      "items",
      {
        schemaId: "items",
        guidField: "guid",
        nameField: "name",
        dataArrayPath: "data",
        elementSchema: itemElementSchema,
      },
    ],
    [
      "research",
      {
        schemaId: "research",
        guidField: "guid",
        nameField: "name",
        dataArrayPath: "data",
        elementSchema: itemElementSchema,
      },
    ],
  ]);
}

// UUID v7 format: xxxxxxxx-xxxx-7xxx-yxxx-xxxxxxxxxxxx (or UUIDv7 time-ordered)
const UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

describe("masterRecordCreation", () => {
  it("creates a new item record and returns node metadata", () => {
    const schemaMetas = buildSchemaMetaMap();
    const columns: Column[] = [
      {
        title: "items",
        data: { data: [] },
      },
    ];

    const result = createMasterRecordForNode("item", columns, schemaMetas);

    expect(result).not.toBeNull();
    expect(result?.masterGuid).toMatch(UUID_RE);
    expect(result?.displayName).toBe("New Item");
    const rows = result?.updatedColumns[0].data.data as Array<{
      guid: string;
      name: string;
    }>;
    expect(rows).toHaveLength(1);
    expect(rows[0].guid).toMatch(UUID_RE);
    expect(rows[0].name).toBe("New Item");
    // masterGuid matches the row's guid
    expect(result?.masterGuid).toBe(rows[0].guid);
  });

  it("generates unique default names for research records", () => {
    const schemaMetas = buildSchemaMetaMap();
    const columns: Column[] = [
      {
        title: "research",
        data: {
          data: [
            { guid: "r-1", name: "New Research" },
            { guid: "r-2", name: "New Research 2" },
          ],
        },
      },
    ];

    const result = createMasterRecordForNode("research", columns, schemaMetas);

    expect(result).not.toBeNull();
    expect(result?.displayName).toBe("New Research 3");
    const rows = result?.updatedColumns[0].data.data as Array<{
      guid: string;
      name: string;
    }>;
    expect(rows).toHaveLength(3);
    expect(rows[0]).toEqual({ guid: "r-1", name: "New Research" });
    expect(rows[1]).toEqual({ guid: "r-2", name: "New Research 2" });
    expect(rows[2].guid).toMatch(UUID_RE);
    expect(rows[2].name).toBe("New Research 3");
    expect(result?.masterGuid).toBe(rows[2].guid);
  });

  it("returns null when the target column does not exist", () => {
    const schemaMetas = buildSchemaMetaMap();
    const columns: Column[] = [];

    const result = createMasterRecordForNode("item", columns, schemaMetas);

    expect(result).toBeNull();
    expect(canCreateMasterRecordForNode("item", columns, schemaMetas)).toBe(
      false,
    );
  });
});
