import { describe, expect, it } from "vitest";

import { resolveDisplayNames } from "./nodeRenderResolvers";
import { buildSchemaMetaMap } from "./schemaMeta";

import type { Column, Schema } from "@moorestech/mooreseditor-plugin-sdk";
import type { Node as ReactFlowNode } from "@xyflow/react";

describe("resolveDisplayNames", () => {
  it("resolves consume labels for research nodes from foreign-key arrays", () => {
    const schemas: Record<string, Schema> = {
      items: {
        type: "object",
        properties: [
          {
            key: "data",
            type: "array",
            items: {
              type: "object",
              properties: [
                { key: "itemGuid", type: "uuid", autoGenerated: true },
                { key: "name", type: "string" },
              ],
            },
          },
        ],
      },
      research: {
        type: "object",
        properties: [
          {
            key: "data",
            type: "array",
            items: {
              type: "object",
              properties: [
                {
                  key: "researchNodeGuid",
                  type: "uuid",
                  autoGenerated: true,
                },
                { key: "researchNodeName", type: "string" },
                {
                  key: "consumeItems",
                  type: "array",
                  items: {
                    type: "object",
                    properties: [
                      {
                        key: "itemGuid",
                        type: "uuid",
                        foreignKey: {
                          schemaId: "items",
                          foreignKeyIdPath: "/data/[*]/itemGuid",
                          displayElementPath: "/data/[*]/name",
                        },
                      },
                      { key: "itemCount", type: "integer" },
                    ],
                  },
                },
              ],
            },
          },
        ],
      },
    };
    const schemaMetas = buildSchemaMetaMap(schemas);

    const jsonData: Column[] = [
      {
        title: "items",
        data: {
          data: [
            { itemGuid: "item-guid-1", name: "Iron Ore" },
            { itemGuid: "item-guid-2", name: "Copper Ore" },
          ],
        },
      },
      {
        title: "research",
        data: {
          data: [
            {
              researchNodeGuid: "research-guid-1",
              researchNodeName: "Smelting",
              consumeItems: [
                { itemGuid: "item-guid-1", itemCount: 30 },
                { itemGuid: "item-guid-2", itemCount: 2 },
              ],
            },
          ],
        },
      },
    ];

    const nodes: ReactFlowNode[] = [
      {
        id: "research-node",
        type: "research",
        position: { x: 0, y: 0 },
        data: {
          masterGuid: "research-guid-1",
          displayName: "Before Resolve",
        },
      },
    ];

    const [resolvedNode] = resolveDisplayNames(nodes, jsonData, schemaMetas);

    expect(resolvedNode.data.displayName).toBe("Smelting");
    expect(resolvedNode.data.consumeLabels).toEqual([
      "Iron Ore x30",
      "Copper Ore x2",
    ]);
  });
});
