import { describe, expect, it } from "vitest";

import {
  buildSchemaRecordIndex,
  buildForeignNameResolver,
  buildSingleRecipeSummary,
  buildRecipeEdgeLabels,
} from "./recipeEdgeLabels";

import type { SchemaMeta } from "./schemaMeta";
import type { RecipeReference } from "../types/nodeGraph";
import type { Column, ObjectSchema } from "@mooreseditor/plugin-sdk";

// --- Test fixtures ---

const ITEM_GUID_A = "aaaa-1111-2222-3333";
const ITEM_GUID_B = "bbbb-1111-2222-3333";
const ITEM_GUID_C = "cccc-1111-2222-3333";
const RECIPE_GUID_1 = "recipe-1111-2222-3333";
const RECIPE_GUID_2 = "recipe-2222-3333-4444";

function makeItemsColumn(): Column {
  return {
    title: "items",
    data: {
      data: [
        { itemGuid: ITEM_GUID_A, name: "Iron Ore" },
        { itemGuid: ITEM_GUID_B, name: "Coal" },
        { itemGuid: ITEM_GUID_C, name: "Iron Ingot" },
      ],
    },
  };
}

function makeItemsMeta(): SchemaMeta {
  return {
    schemaId: "items",
    guidField: "itemGuid",
    nameField: "name",
    dataArrayPath: "data",
    elementSchema: {
      type: "object",
      properties: [
        { key: "itemGuid", type: "uuid", autoGenerated: true },
        { key: "name", type: "string" },
      ],
    },
  };
}

function makeCraftRecipeElementSchema(): ObjectSchema {
  return {
    type: "object",
    properties: [
      { key: "recipeGuid", type: "uuid", autoGenerated: true },
      { key: "recipeName", type: "string" },
      {
        key: "outputItem",
        type: "uuid",
        foreignKey: {
          schemaId: "items",
          foreignKeyIdPath: "",
          displayElementPath: "",
        },
      },
      { key: "outputCount", type: "integer" },
      {
        key: "inputMaterials",
        type: "array",
        items: {
          type: "object",
          properties: [
            {
              key: "itemGuid",
              type: "uuid",
              foreignKey: {
                schemaId: "items",
                foreignKeyIdPath: "",
                displayElementPath: "",
              },
            },
            { key: "itemCount", type: "integer" },
          ],
        },
      },
    ],
  };
}

function makeMachineRecipeElementSchema(): ObjectSchema {
  return {
    type: "object",
    properties: [
      { key: "recipeGuid", type: "uuid", autoGenerated: true },
      {
        key: "resultItem",
        type: "uuid",
        foreignKey: {
          schemaId: "items",
          foreignKeyIdPath: "",
          displayElementPath: "",
        },
      },
      { key: "resultCount", type: "integer" },
    ],
  };
}

function makeCraftRecipesMeta(): SchemaMeta {
  return {
    schemaId: "craftRecipes",
    guidField: "recipeGuid",
    nameField: "recipeName",
    dataArrayPath: "data",
    elementSchema: makeCraftRecipeElementSchema(),
  };
}

function makeMachineRecipesMeta(): SchemaMeta {
  return {
    schemaId: "machineRecipes",
    guidField: "recipeGuid",
    nameField: null,
    dataArrayPath: "data",
    elementSchema: makeMachineRecipeElementSchema(),
  };
}

function makeCraftRecipesColumn(): Column {
  return {
    title: "craftRecipes",
    data: {
      data: [
        {
          recipeGuid: RECIPE_GUID_1,
          recipeName: "Smelt Iron",
          outputItem: ITEM_GUID_C,
          outputCount: 1,
          inputMaterials: [
            { itemGuid: ITEM_GUID_A, itemCount: 2 },
            { itemGuid: ITEM_GUID_B, itemCount: 3 },
          ],
        },
      ],
    },
  };
}

function makeMachineRecipesColumn(): Column {
  return {
    title: "machineRecipes",
    data: {
      data: [
        {
          recipeGuid: RECIPE_GUID_2,
          resultItem: ITEM_GUID_C,
          resultCount: 5,
        },
      ],
    },
  };
}

function makeAllColumns(): Column[] {
  return [
    makeItemsColumn(),
    makeCraftRecipesColumn(),
    makeMachineRecipesColumn(),
  ];
}

function makeAllSchemaMetas(): Map<string, SchemaMeta> {
  return new Map([
    ["items", makeItemsMeta()],
    ["craftRecipes", makeCraftRecipesMeta()],
    ["machineRecipes", makeMachineRecipesMeta()],
  ]);
}

// --- Tests ---

describe("buildSchemaRecordIndex", () => {
  it("indexes records by guid field", () => {
    const jsonData = makeAllColumns();
    const metas = makeAllSchemaMetas();

    const index = buildSchemaRecordIndex("items", jsonData, metas);

    expect(index.size).toBe(3);
    expect(index.get(ITEM_GUID_A)).toEqual({
      itemGuid: ITEM_GUID_A,
      name: "Iron Ore",
    });
    expect(index.get(ITEM_GUID_B)).toEqual({
      itemGuid: ITEM_GUID_B,
      name: "Coal",
    });
  });

  it("returns empty map for unknown schema", () => {
    const index = buildSchemaRecordIndex(
      "nonexistent",
      makeAllColumns(),
      makeAllSchemaMetas(),
    );
    expect(index.size).toBe(0);
  });

  it("returns empty map when schema has no guidField", () => {
    const metas = new Map<string, SchemaMeta>([
      ["items", { ...makeItemsMeta(), guidField: null }],
    ]);
    const index = buildSchemaRecordIndex("items", makeAllColumns(), metas);
    expect(index.size).toBe(0);
  });
});

describe("buildForeignNameResolver", () => {
  it("resolves guid to name", () => {
    const resolver = buildForeignNameResolver(
      makeAllColumns(),
      makeAllSchemaMetas(),
    );
    expect(resolver("items", ITEM_GUID_A)).toBe("Iron Ore");
    expect(resolver("items", ITEM_GUID_B)).toBe("Coal");
    expect(resolver("items", ITEM_GUID_C)).toBe("Iron Ingot");
  });

  it("returns null for unknown guid", () => {
    const resolver = buildForeignNameResolver(
      makeAllColumns(),
      makeAllSchemaMetas(),
    );
    expect(resolver("items", "unknown-guid")).toBeNull();
  });

  it("returns null for unknown schema", () => {
    const resolver = buildForeignNameResolver(
      makeAllColumns(),
      makeAllSchemaMetas(),
    );
    expect(resolver("nonexistent", ITEM_GUID_A)).toBeNull();
  });

  it("caches results on second call", () => {
    const resolver = buildForeignNameResolver(
      makeAllColumns(),
      makeAllSchemaMetas(),
    );
    const first = resolver("items", ITEM_GUID_A);
    const second = resolver("items", ITEM_GUID_A);
    expect(first).toBe(second);
    expect(first).toBe("Iron Ore");
  });

  it("falls back to shortGuid when nameField is missing", () => {
    const metas = new Map<string, SchemaMeta>([
      ["items", { ...makeItemsMeta(), nameField: null }],
    ]);
    const resolver = buildForeignNameResolver(makeAllColumns(), metas);
    // Without nameField, it falls back to the guid itself (rawLabel = id),
    // but since guid is a string with length > 0, it uses the guid as label
    expect(resolver("items", ITEM_GUID_A)).toBe(ITEM_GUID_A);
  });
});

describe("buildSingleRecipeSummary", () => {
  function makeRecipeRecords(): Map<
    string,
    Map<string, Record<string, unknown>>
  > {
    const craftIndex = new Map<string, Record<string, unknown>>();
    craftIndex.set(RECIPE_GUID_1, {
      recipeGuid: RECIPE_GUID_1,
      recipeName: "Smelt Iron",
      outputItem: ITEM_GUID_C,
      outputCount: 1,
      inputMaterials: [
        { itemGuid: ITEM_GUID_A, itemCount: 2 },
        { itemGuid: ITEM_GUID_B, itemCount: 3 },
      ],
    });
    const machineIndex = new Map<string, Record<string, unknown>>();
    machineIndex.set(RECIPE_GUID_2, {
      recipeGuid: RECIPE_GUID_2,
      resultItem: ITEM_GUID_C,
      resultCount: 5,
    });
    return new Map([
      ["craftRecipes", craftIndex],
      ["machineRecipes", machineIndex],
    ]);
  }

  function makeResolver(): (schemaId: string, guid: string) => string | null {
    return buildForeignNameResolver(makeAllColumns(), makeAllSchemaMetas());
  }

  it("produces vertical format for craftRecipe", () => {
    const ref: RecipeReference = {
      edgeType: "craftRecipe",
      masterGuid: RECIPE_GUID_1,
    };
    const result = buildSingleRecipeSummary(
      ref,
      makeRecipeRecords(),
      makeAllSchemaMetas(),
      makeResolver(),
    );

    expect(result).toBe("Iron Ore 2\nCoal 3\n↓\nIron Ingot 1");
  });

  it("produces vertical format for machineRecipe", () => {
    const ref: RecipeReference = {
      edgeType: "machineRecipe",
      masterGuid: RECIPE_GUID_2,
    };
    const result = buildSingleRecipeSummary(
      ref,
      makeRecipeRecords(),
      makeAllSchemaMetas(),
      makeResolver(),
    );

    expect(result).toBe("↓\nIron Ingot 5");
  });

  it("falls back to 'Craft:shortGuid' when record not found", () => {
    const ref: RecipeReference = {
      edgeType: "craftRecipe",
      masterGuid: "missing-guid-1234-5678",
    };
    const result = buildSingleRecipeSummary(
      ref,
      makeRecipeRecords(),
      makeAllSchemaMetas(),
      makeResolver(),
    );

    expect(result).toBe("Craft:missing-");
  });

  it("falls back to 'Machine:shortGuid' when record not found", () => {
    const ref: RecipeReference = {
      edgeType: "machineRecipe",
      masterGuid: "missing-guid-1234-5678",
    };
    const result = buildSingleRecipeSummary(
      ref,
      makeRecipeRecords(),
      makeAllSchemaMetas(),
      makeResolver(),
    );

    expect(result).toBe("Machine:missing-");
  });

  it("falls back to nameField when no outputs found", () => {
    const craftIndex = new Map<string, Record<string, unknown>>();
    craftIndex.set(RECIPE_GUID_1, {
      recipeGuid: RECIPE_GUID_1,
      recipeName: "My Recipe",
      // no outputItem, no inputMaterials
    });
    const records = new Map([
      ["craftRecipes", craftIndex],
      ["machineRecipes", new Map<string, Record<string, unknown>>()],
    ]);
    const ref: RecipeReference = {
      edgeType: "craftRecipe",
      masterGuid: RECIPE_GUID_1,
    };
    const result = buildSingleRecipeSummary(
      ref,
      records,
      makeAllSchemaMetas(),
      makeResolver(),
    );

    expect(result).toBe("My Recipe");
  });

  it("falls back to shortGuid when no outputs and no name", () => {
    const craftIndex = new Map<string, Record<string, unknown>>();
    craftIndex.set(RECIPE_GUID_1, {
      recipeGuid: RECIPE_GUID_1,
      // no recipeName, no outputItem, no inputMaterials
    });
    const records = new Map([
      ["craftRecipes", craftIndex],
      ["machineRecipes", new Map<string, Record<string, unknown>>()],
    ]);
    const ref: RecipeReference = {
      edgeType: "craftRecipe",
      masterGuid: RECIPE_GUID_1,
    };
    const result = buildSingleRecipeSummary(
      ref,
      records,
      makeAllSchemaMetas(),
      makeResolver(),
    );

    expect(result).toBe("recipe-1");
  });

  it("shows count value when count is 1", () => {
    const machineIndex = new Map<string, Record<string, unknown>>();
    machineIndex.set(RECIPE_GUID_2, {
      recipeGuid: RECIPE_GUID_2,
      resultItem: ITEM_GUID_C,
      resultCount: 1,
    });
    const records = new Map([
      ["craftRecipes", new Map<string, Record<string, unknown>>()],
      ["machineRecipes", machineIndex],
    ]);
    const ref: RecipeReference = {
      edgeType: "machineRecipe",
      masterGuid: RECIPE_GUID_2,
    };
    const result = buildSingleRecipeSummary(
      ref,
      records,
      makeAllSchemaMetas(),
      makeResolver(),
    );

    expect(result).toBe("↓\nIron Ingot 1");
  });
});

describe("buildRecipeEdgeLabels", () => {
  it("returns labels for multiple recipe refs", () => {
    const refs: RecipeReference[] = [
      { edgeType: "craftRecipe", masterGuid: RECIPE_GUID_1 },
      { edgeType: "machineRecipe", masterGuid: RECIPE_GUID_2 },
    ];
    const labels = buildRecipeEdgeLabels(
      refs,
      makeAllColumns(),
      makeAllSchemaMetas(),
    );

    expect(labels).toHaveLength(2);
    expect(labels[0]).toBe("Iron Ore 2\nCoal 3\n↓\nIron Ingot 1");
    expect(labels[1]).toBe("↓\nIron Ingot 5");
  });

  it("returns empty array for empty refs", () => {
    const labels = buildRecipeEdgeLabels(
      [],
      makeAllColumns(),
      makeAllSchemaMetas(),
    );
    expect(labels).toHaveLength(0);
  });
});
