import type { Schema, ObjectSchema } from "@moorestech/mooreseditor-plugin-sdk";

export interface SchemaMeta {
  schemaId: string;
  guidField: string | null;
  nameField: string | null;
  dataArrayPath: string;
  elementSchema: ObjectSchema | null;
}

/**
 * Dynamically extract meta information from a schema.
 * Does not hardcode any specific schema ID or field name.
 */
export function extractSchemaMeta(
  schemaId: string,
  schema: Schema,
): SchemaMeta {
  const meta: SchemaMeta = {
    schemaId,
    guidField: null,
    nameField: null,
    dataArrayPath: "data",
    elementSchema: null,
  };

  if (!("type" in schema) || schema.type !== "object") return meta;

  const objSchema = schema as ObjectSchema;

  // Find the array property in the root object
  const arrayProp = objSchema.properties?.find(
    (p) => "type" in p && (p as any).type === "array",
  );
  if (arrayProp) {
    meta.dataArrayPath = arrayProp.key;
    const { key: _key, ...arraySchema } = arrayProp;
    if (
      "items" in arraySchema &&
      arraySchema.items &&
      "type" in arraySchema.items &&
      arraySchema.items.type === "object"
    ) {
      meta.elementSchema = arraySchema.items as ObjectSchema;

      // GUID field: type: uuid + autoGenerated: true
      const guidProp = meta.elementSchema.properties?.find(
        (p) =>
          "type" in p && (p as any).type === "uuid" && (p as any).autoGenerated,
      );
      if (guidProp) meta.guidField = guidProp.key;

      // Name field: prefer a string field whose key contains "name",
      // otherwise fall back to first string field that isn't the GUID
      const stringProps = meta.elementSchema.properties?.filter(
        (p) =>
          "type" in p &&
          (p as any).type === "string" &&
          p.key !== meta.guidField,
      );
      const nameByKey = stringProps?.find((p) =>
        p.key.toLowerCase().includes("name"),
      );
      const nameProp = nameByKey ?? stringProps?.[0];
      if (nameProp) meta.nameField = nameProp.key;
    }
  }

  return meta;
}

/**
 * Build SchemaMeta map for all loaded schemas
 */
export function buildSchemaMetaMap(
  schemas: Record<string, Schema>,
): Map<string, SchemaMeta> {
  const map = new Map<string, SchemaMeta>();
  for (const [id, schema] of Object.entries(schemas)) {
    map.set(id, extractSchemaMeta(id, schema));
  }
  return map;
}
